### ISSUE TITLE
No remote audio/video, or screen record seen in remote section

### ISSUE THREAD

**Issue by depeshpo** [Dirvann/mediasoup-sfu-webrtc-video-rooms#3]
I was experimenting with the project to learn how mediasoup works. Found that, No remote source found in remote section. I have already installed all the packages and updated config.js file's mediasoup.webRtcTransport.listenIps[0].annonuncedIp to my local IP. The local section is working fine but the problem is it won't display the remote section.

**Comment by Dirvann** [comment]
Thanks you for trying the project out. I have some questions:
- Did you try it out on different machines on the same network? 
- If so, did you always use the IP address you set (internal network IP I suppose) in your browser and not localhost as address?
- Are there any logs in your browser console? And what about your network tab in inspect elements?

**Comment by depeshpo** [comment]
Sorry for the late response.
Answers for your three questions:

- I tried this in the same browser (Google Chrome 85.0.4183.83) as different tabs.
- For the second question, I've not tried this in multiple systems
- I did not found any unsuccessful or error network message in the network section but found one warning in the browser console (no any other errors) 
`DevTools failed to load SourceMap: Could not load content for chrome-extension://bpcagekijmfcocgjlnnhpdogbplajjfn/lib/jquery.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
`
Is there anything I am missing from the installation manuals? or if you have been through this kind of scenario it will be a great help for me.

**Comment by Dirvann** [comment]
- if you use it on the same pc anyway you can just use 127.0.0.1
- The jquery message has nothing to do with this code. As Jquery is not used at all. It's part of an extension in your browser probably.
- never had a problem. But there is probably something wrong in the configurations or your firewall that blocks the ports you need.

**Comment by akindizayn1** [comment]
Hello, the same problem exists with my setup. There is local view but I cannot see remote images. I tried in different browsers, only local image is available. Can you help?
<img width="1178" alt="Ekran Resmi 2020-10-06 23 06 23" src="https://user-images.githubusercontent.com/72012423/95254491-a0895180-0828-11eb-9166-b5ab856cf4e5.png">

**Comment by Dirvann** [comment]
@akindizayn1 Are you using a mac? because I haven't tested the code on a mac.

**Comment by Dirvann** [comment]
@akindizayn1 I also noticed the audio and video devices aren't loaded yet. This happens when the audio video request hadn't been accepted before. So reloading the page should solve the issue.

**Comment by pingqiaotoufu** [comment]
> I was experimenting with the project to learn how mediasoup works. Found that, No remote source found in remote section. I have already installed all the packages and updated config.js file's mediasoup.webRtcTransport.listenIps[0].annonuncedIp to my local IP. The local section is working fine but the problem is it won't display the remote section.

You need to config the mediasoup.
in 
/src/config.js
change here
announcedIp:'0.0.0.0' // replace by public IP address

**Comment by miroslavpejic85** [comment]
@akindizayn1, @Dirvann 
What I see is that you `don't have the list of audio and video devices`, 
therefore, passing an `empty deviceId` to the [produce](https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/blob/master/public/RoomClient.js#L250) seems not like it :)
After this fix: https://github.com/Dirvann/mediasoup-sfu-webrtc-video-rooms/issues/12#issue-950841490
Seems ok on my chrome (Version 92.0.4515.107 (Build official) (x86_64)) On macOS Big Sure 11.4.
<img width="549" alt="chrome-sfu" src="https://user-images.githubusercontent.com/70838434/126696245-d816c42a-9eed-4e53-b1ce-e3275078f846.png">

**Comment by miroslavpejic85** [comment]
I also did some cross-testing to see the compatibility between the various browsers. I am attaching the output here:

<img width="661" alt="test-cases" src="https://user-images.githubusercontent.com/70838434/126869499-c2e66e8a-8ab6-46fb-8e56-46785bf5f503.png">

Regards

**Comment by miroslavpejic85** [comment]
@Dirvann 

I also did some `cross-testing` to see the compatibility between the various browsers. I am attaching the output here:

|  BROWSERS     |  VERSION                                                       | OS                  |
|---------------|----------------------------------------------------------------|---------------------|
| `SAFARI`      | 14.1.2 (16611.3.10.1.3)                                        | macOS Big Sure 11.5 |
| `CHROME`      | 92.0.4515.107 (Build official) (x86_64)                        | macOS Big Sure 11.5 |
| `FIREFOX`     | 90.0.2 (64 bit)                                                | macOS Big Sure 11.5 |
| `OPERA`       | 77.0.4054.277 (x86_64)                                         | macOS Big Sure 11.5 |
| `EDGE`        | 92.0.902.55 (Build official) (x86_64)                          | macOS Big Sure 11.5 |
| `BRAVE`       | 1.27.108 Chromium: 92.0.4515.107 (Build official) (x86_64)     | macOS Big Sure 11.5 |

<br>

|  BROWSERS     |  SAFARI  | CHROME   | FIREFOX  |  OPERA   | EDGE     | BRAVE    |
|---------------|----------|----------|----------|----------|----------|----------|
| `SAFARI`      | `KO`     | OK       | OK       | OK       | OK       | OK       |
| `CHROME`      | OK       | OK       | OK       | OK       | OK       | OK       |
| `FIREFOX`     | OK       | OK       | OK       | OK       | OK       | OK       |
| `OPERA`       | OK       | OK       | OK       | OK       | OK       | OK       |
| `EDGE`        | OK       | OK       | OK       | OK       | OK       | OK       |
| `BRAVE`       | OK       | OK       | OK       | OK       | OK       | OK       |


Regards

**Comment by robojiannis** [comment]
I'm having this issue too, but only with firefox (both windows and mac). Firefox sends the stream correctly, but the remote streams aren't shown. 
Same setup works on chrome & safari both on localhost and on a live server with a public IP.

i tried enabling media.peerconnection.ice.loopback as described [here](https://mediasoup.discourse.group/t/firefox-ice-failed-add-a-stun-server-and-see-about-webrtc-for-more-details/805/9), but this didn't solve it. 

Any clues?

**Comment by miroslavpejic85** [comment]
Seems that problem is on latest `FIREFOX  91.0 (64bit)` when I tested it, I used `90.0.2 (64 bit)` and all worked perfectly...

**Comment by robojiannis** [comment]
you're right! I'm digging through the [mediasoup demo](https://v3demo.mediasoup.org/) code, since it's working there. no success so far though

**Comment by miroslavpejic85** [comment]
Ok found the problem, is all ok also for `FIREFOX` this is the config you need to have:

Test on Local PC:

FIREFOX not like `127.0.0.1` as `announcedIp`

```js
const os = require('os');
const ifaces = os.networkInterfaces();

const getLocalIp = () => {
    let localIp = '127.0.0.1';
    Object.keys(ifaces).forEach((ifname) => {
        for (const iface of ifaces[ifname]) {
            // Ignore IPv6 and 127.0.0.1
            if (iface.family !== 'IPv4' || iface.internal !== false) {
                continue;
            }
            // Set the local ip to the first IPv4 address found and exit the loop
            localIp = iface.address;
            return;
        }
    });
    return localIp;
};

module.exports = {
    listenIp: '0.0.0.0',

    ...

            listenIps: [
                {
                    ip: '0.0.0.0',
                    announcedIp: getLocalIp(), // replace by public IP address
                },
            ],
```

Test outside


```js

module.exports = {
    listenIp: '0.0.0.0',

    ...

            listenIps: [
                {
                    ip: '0.0.0.0',
                    announcedIp: 'Your public IP address'
                },
            ],

```

Remember also to open ports specified here: `rtcMinPort:rtcMaxPort`

**Comment by robojiannis** [comment]
that's great, it now indeed works locally thanks!!
I have following ports open ortcMinPort: 10000, rtcMaxPort: 10100 and a public static IP that works when live. 

Unfortunately though the issue occurs when uploading on the server and going through the public static IP although it works properly on chrome/firefox. Any hints about that?

**Comment by miroslavpejic85** [comment]
Yeah, good :)
`10000` - `10100` is `not 2 ports`, it's a `range` from 10000 to 10100 (`10000:10100`)
Maybe IMHO better will be to use this port range `40000:41000` [ref](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)

**Comment by robojiannis** [comment]
thanks, I'm not that versed in server/mediasoup stuff yet :) I changed the port range as you suggested, but firefox on the static public ip server is still not playing along.

**Comment by miroslavpejic85** [comment]
Don't worry, I'm beginner too as far as `mediasoup` is concerned ;)

Ok you opened the ranges port but did it you `forwarded` to the `private ip` where the `app - mediasoup` server is `running`?

Something like this

|  Name         |  Protocol  | Port Wan    | Port Lan    |  IP Destination   | 
|---------------|------------|-------------|-------------|-------------------|
| `Mediasoup`   | `TCP/UDP`  | 10000:10100 | 10000:10100 | `Your Local IP`   |

**Comment by robojiannis** [comment]
thanks for staying with me :)

Here's my config file on the live server, where DIGITAL_OCEAN_PUBLIC_IP is the floating IP of digital ocean. Strangely, it works on chrome/safari.




```
const os = require('os');
const ifaces = os.networkInterfaces();

const getLocalIp = () => {
    let localIp = "127.0.0.1";
    Object.keys(ifaces).forEach((ifname) => {
        for (const iface of ifaces[ifname]) {
            // Ignore IPv6 and 127.0.0.1
            if (iface.family !== 'IPv4' || iface.internal !== false) {
                continue;
            }
            // Set the local ip to the first IPv4 address found and exit the loop
            localIp = iface.address;
            return;
        }
    });
    return localIp;
};

module.exports = {
    listenIp: '0.0.0.0',
    listenPort: 3016,
    sslCrt: 'ssl/cert.pem',
    sslKey: 'ssl/key.pem',
    
    mediasoup: {
      // Worker settings
      numWorkers : Object.keys(os.cpus()).length,
      worker: {
        rtcMinPort: 40000,
        rtcMaxPort: 41000,
        logLevel: 'warn',
        logTags: [
          'info',
          'ice',
          'dtls',
          'rtp',
          'srtp',
          'rtcp',
          'rtx',
          'bwe',
          'score',
          'simulcast',
          'svc'
        ],
      },
      // Router settings
      router: {
        mediaCodecs:
          [
            {
              kind: 'audio',
              mimeType: 'audio/opus',
              clockRate: 48000,
              channels: 2
            },
            {
              kind: 'video',
              mimeType: 'video/VP8',
              clockRate: 90000,
              parameters:
                {
                  'x-google-start-bitrate': 1000
                }
            },
          ]
      },
    // WebRtcTransport settings
    webRtcTransport: {
        listenIps: [
          {
            ip: '0.0.0.0',     
            announcedIp: DIGITAL_OCEAN_PUBLIC_IP,
            enableTcp:true,
            enableUdp: true
          }
        ],
        maxIncomingBitrate: 1500000,
        initialAvailableOutgoingBitrate: 1000000
    },
    }
  };
  
```

**Comment by miroslavpejic85** [comment]
My pleasure, So the problem is only for `Firefox`....

if you `delete` this 2 params something change?
```js
enableTcp: true,
enableUdp: true
```
You can Try to see also if someone deployed it on `DIGITAL OCEAN` in the mediasoup forum, and if you found something interesting, you can post here :) 

Actually, just To test it outside a network, I'm using [ngrok](https://ngrok.com) on my Local PC...

**Comment by robojiannis** [comment]
I currently run 1CPU, 2GB RAM droplet. I've tested with 3 rooms, 7 users per room and had no performance issues. 

Removing those two 
```
enableTcp: true,
enableUdp: true
```
threw an error about missing stun servers. 

It's strange because i can see the firefox stream on chrome, but I can't see the chrome stream on firefox. I'll keep you posted once resolved :)

**Comment by robojiannis** [comment]
i figured it out. chrome/safari are OK with the floating IP of the droplet, but firefox needs the static ipv4 not the floating one. Don't know why, but it works :)

**Comment by miroslavpejic85** [comment]
Yeah good, so Firefox on DigitalOcean have this issue right? 
What I understand, DigitalOcean `floating IPs` are `publicly accessible static IP`. 
You can set also static ipv4? Both? Or only one of this? O.o

**Comment by robojiannis** [comment]
Yes, the droplet has a static ipv4 by default. I'm not sure if it's public too, but it certainly works now ٩( ᐛ )و
