### ISSUE TITLE
Bypassing login screen using URL params, no remote feed displayed

### ISSUE THREAD

**Issue by samames** [Dirvann/mediasoup-sfu-webrtc-video-rooms#6]
Please see my issue posted here: https://stackoverflow.com/questions/65943776/not-recieving-remote-video-stream-when-accessing-by-directly-modifying-url-param

I'm clueless as to the cause and would be grateful for any support. 

Many thanks.

**Comment by bhayanisumit** [comment]
changes announcedIp in config..

**Comment by Dirvann** [comment]
thanks @miroslavpejic85 for the solution
